name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            bug
            chore
            feature
          requireScope: true
          ignoreLabels: |
            dependencies
          headerPattern: '^SC-\d{4,}\: (\w*)(?:\(([\w\$\.\-\* ]*)\))?\: (.*)$'

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            ## :rocket: You opened a pull request and that's awesome! :rocket:
            
            #### :poop: ...but your PR title doesn't meet our standards :poop:
            
            We require pull request titles to be prefixed with the shortcut number and then to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.
            
            ### #xamples:
            #### :white_check_mark: GOOD: 
            SC-1234: chore(engine): Foo the bar
            
            #### :x: BAD: 
            Foo the bar
            
            
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:   
          header: pr-title-lint-error
          delete: true

